[tool.poetry]
name = "kas-moe-back"
version = "0.1.0"
description = "KAS MOE BackEnd"
authors = ["Federico Corval√°n <hi@fedr.cc>"]
license = "MPL-2.0"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.63.0"
uvicorn = {extras = ["standard"], version = "^0.13.4"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
